/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f6",
        "inverse-on-surface": "#f1f1ed",
        "surface-container-high": "#e8e8e5",
        "on-surface-variant": "#424843",
        "tertiary-fixed": "#ccebc8",
        "error-container": "#ffdad6",
        "surface-variant": "#e2e3df",
        "on-tertiary-fixed-variant": "#334d34",
        "surface-bright": "#faf9f6",
        "secondary-container": "#e2e0d7",
        "on-primary-fixed-variant": "#2f4d39",
        "surface-dim": "#dadad7",
        "tertiary": "#1b341d",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#adcfb4",
        "background": "#faf9f6",
        "outline": "#727972",
        "surface-container-highest": "#e2e3df",
        "outline-variant": "#c2c8c0",
        "secondary-fixed-dim": "#c9c6be",
        "on-background": "#1a1c1a",
        "primary-fixed": "#c8ebd0",
        "surface-container": "#eeeeea",
        "on-primary-fixed": "#022110",
        "on-tertiary-container": "#9dba9a",
        "tertiary-fixed-dim": "#b0ceae",
        "on-secondary-container": "#64635c",
        "on-tertiary": "#ffffff",
        "surface-tint": "#466550",
        "secondary": "#5f5f58",
        "inverse-surface": "#2f312f",
        "on-secondary-fixed": "#1c1c17",
        "on-surface": "#1a1c1a",
        "primary": "#163422",
        "on-error-container": "#93000a",
        "on-primary-container": "#99baa1",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#474741",
        "primary-container": "#2d4b37",
        "tertiary-container": "#314b32",
        "error": "#ba1a1a",
        "secondary-fixed": "#e5e2da",
        "on-tertiary-fixed": "#07200b",
        "inverse-primary": "#adcfb4",
        "surface-container-low": "#f4f4f0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "unit": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-display": ["Manrope"],
        "label-sm": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Manrope"],
        "headline-md": ["Manrope"],
        "sans": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
